export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const OPEN_CART_DIALOG = 'OPEN_CART_DIALOG'
export const UPDATE_PRODUCT_LIST='UPDATE_PRODUCT_LIST';
export const UPDATE_PRODUCT_LIST_ON_RATING= 'UPDATE_PRODUCT_LIST_ON_RATING'
export const UPDATE_PRODUCT_LIST_ON_PRICE= 'UPDATE_PRODUCT_LIST_ON_PRICE'

